version: "2"
services:
  elb:
    image: haproxy
    ports:
      - "80:80"
    volumes:
      - "./haproxy:/usr/local/etc/haproxy"
#    networks:
#      - web
#      - no-internet
#    network_mode: host

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    #ports:
    # – "32400:32400/tcp"
    # – "3005:3005/tcp"
    # – "8324:8324/tcp"
    # – "32469:32469/tcp"
    # – "1900:1900/udp"
    # – "32410:32410/udp"
    # – "32412:32412/udp"
    # – "32413:32413/udp"
    # – "32414:32414/udp"
    volumes:
      - /media/plex/movies:/movies
      - /docker/plex/library:/config
#      - /media/plex/tvseries:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    restart: always
#    networks:
#      - no-internet
    cap_drop:
      - NET_RAW
      - NET_ADMIN
#networks:
#  web:
#    external: true
#  no-internet:
#    driver: bridge
#    internal: true # Block internet access
